DEV-1668 re allow input or output feature list to be a featureset
fennel-ai/client pull request #260
Opened 2023-08-10 21:58 UTC by zsid60

2023-08-10 22:18 UTC, bothra90 requested changes
We don't want to allow input list to have featuresets since that can break existing applications using the REST API. Only the output list should be allowed to have featuresets

2023-08-10 23:12 UTC, zsid60 commented
@bothra90: fixed to only change for output

2023-08-13 05:35 UTC, bothra90 approved these changes

2023-08-14 18:45 UTC, zsid60 commented
TODO: update changelog / version

2023-08-14 21:50 UTC, merged