dropnull
fennel-ai/client pull request #285
Opened 2023-10-05 08:51 UTC by thaqibm

2023-10-09 16:48 UTC, aditya-nambiar requested changes

2023-10-09 16:48 UTC, aditya-nambiar commented on fennel/datasets/datasets.py
> +def fennel_optional_inner(type_):
I feel this function deserves a better name

2023-10-09 16:48 UTC, aditya-nambiar commented on fennel/datasets/datasets.py
> +        if obj.columns is None or len(obj.columns) == 0:
We should allow dropnull on the entire dataset too? Which would basically create dropnulls for any optional column in the dataset, if there are no optional columns then we can throw an error

2023-10-12 23:53 UTC, aditya-nambiar commented
Can you add documentation and bump the version

2023-10-12 23:53 UTC, aditya-nambiar approved these changes

2023-10-14 04:51 UTC, nikhilgarg28 reviewed
FYI - the recommended way to write commit messages is as follows:

<module>: <upto 72 chars in total of description in imperative form>

<more details>

Module can literally be the name of a module or logical module. In this case, 'operator' may be a good name. The summary should be imperative e.g. 'add dropnull, fix docs for select' vs 'added dropnull' or 'dropnull'.

2023-10-14 04:51 UTC, nikhilgarg28 commented on docs/pages/api-reference/operators.md
> +Fennel allows you to drop null values from columns of a dataset using the `dropnull` operator.
We should mention that this also changes the type of the column from `Option[T]` to `T`.

2023-10-14 04:51 UTC, nikhilgarg28 commented on docs/pages/api-reference/operators.md
> +1. `columns: List[str]` - positional argument, that specifies the list of columns to apply dropnull on from the dataset.
Can user leave arguments to `dropnull` empty? If so, worth documenting that here?

2023-10-14 04:51 UTC, nikhilgarg28 commented on docs/pages/api-reference/operators.md
> +1. `columns: List[str]` - positional argument, that specifies the list of columns to apply dropnull on from the dataset.
We should also mention that this operator could take an actual list of names or simply names without list literal (not exactly like this, hopefully in better language). Also, please do the same for select and drop if we haven't already.

2023-10-16 21:34 UTC, merged