[DEV 4347] Added support for filter in preproc
fennel-ai/client pull request #498
Opened 2024-06-24 10:51 UTC by nonibansal

2024-06-24 23:51 UTC, aditya-nambiar commented
We have a function called lambda_to_python_regular_func that helps convert lambda to regular func and is used in filter. Can we use that ?

2024-06-24 23:51 UTC, aditya-nambiar commented
lambda's tend to break when they are multi line/nested lambda etc, can you add some test cases around them ? if you use the above lib function I'm hopeful it would work out

2024-06-24 23:51 UTC, aditya-nambiar requested changes

2024-06-25 07:54 UTC, nonibansal commented on docs/examples/concepts/source.py
> +        filter=lambda x: x["skuid"] >= 1000,
renamed

2024-06-29 18:54 UTC, nikhilgarg28 approved these changes
Didn't review carefully since @aditya-nambiar had done that. 
That said, want to make sure the following are done:
1. Multiline lambdas work
2. If a user passes a function (not lambda) along with includes, that works
3. Preproc works on mock client too.

If any of these don't work, could you plz address them in a follow up commit.

2024-07-01 03:46 UTC, nonibansal commented
> Didn't review carefully since @aditya-nambiar had done that. That said, want to make sure the following are done:
> 
> 1. Multiline lambdas work
> 2. If a user passes a function (not lambda) along with includes, that works
> 3. Preproc works on mock client too.
> 
> If any of these don't work, could you plz address them in a follow up commit.

@aditya-nambiar Made the change to allow multi line lambda.
Function is also allowed in filter along with lambda.
Preproc filter works on mock client too.

2024-07-01 15:45 UTC, merged